project_id = "rgehktwlrbytyvtfrhms"

[functions.gustav-chat]
verify_jwt = false

[functions.rate-limit]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.csv-import]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.generate-k7-xml]
verify_jwt = false
